### ISSUE TITLE
Hard to read navbar (mobile)

### ISSUE THREAD

**Issue by adam-ius** [virtrolio/virtrolio-site#18]
**Mobile version** (portrait orientation)
Clicking on the top-right icon that brings up the menu just brings up text that's hard to read.  
Probably an issue with adjusting the background behind the navbar.
![navbar-issue](https://user-images.githubusercontent.com/58651279/85337445-7e083e00-b4ae-11ea-9647-8a93577bfd17.png)

**Comment by ricetech** [comment]
This issue was resolved in commit [aab362e](https://github.com/virtrolio/virtrolio-site/commit/aab362e65e991bd21b3e3194a6f2195ffbcafb41).
