### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by ArvindN0** [virtrolio/virtrolio-site#26]
Replace this message:
Create a virtrolio
It's easy to create a virtrolio! Sign in with your Google account and a custom virtrolio link will be generated for you. Share this link with your friends so they can sign your virtrolio.

With this:
Create a virtrolio
It's easy to create a virtrolio! Sign in with your Google account and a custom virtrolio link will be generated for you. Share this link with your friends and they'll be able to sign it.

**Comment by ricetech** [comment]
On the homepage, I feel like it's a better idea to restate the name a couple of times to keep it fresh in their minds. I prefer the current wording, personally.
