### ISSUE TITLE
Move sign up button to top of homepage

### ISSUE THREAD

**Issue by ningsongshen** [virtrolio/virtrolio-site#52]
**Describe the bug**
It seems that on most product websites there is a call to action button somewhere in the big top banner of the front page. But you guys don't have one. So it may be that when users finish reading the homepage, they scroll to top, and can't find anywhere to sign up. They have to scroll down a bit to find it. It maybe better instead to have a sign up button at the top.

Not an expert in user behaviour, but that is how I behave.

**Comment by GuyInFridge** [comment]
@janakitti can add a 'Sign In' button on the right hand side of the navbar when logged out. We'll get to work!

**Comment by ricetech** [comment]
@GuyInFridge @janakitti If we add a sign-in button to the top of the navbar, how can we alert the user of their required agreement to the ToS and Privacy Policy?

**Comment by DabeerAzeez** [comment]
Fair. We could make the sign-in button scroll down to the other sign-in button on the home page?

**Comment by DronHazra** [comment]
#65 does this work?

**Comment by ricetech** [comment]
We added a second sign-in button to the bottom of the homepage in PR #79. This allows the user to sign in/sign up once they finish reading the homepage without sticking something in the middle of the big flashy banner.

The original sign in/sign up button remains in its present location as well.
