### ISSUE TITLE
Third-party markdown editors

### ISSUE THREAD

**Issue by ningsongshen** [virtrolio/virtrolio-site#55]
This if for if you guys ever get lazy and don't want to work on the editor lol (but otherwise the editor is ~~fine~~ great!)

There are plenty of third-party markdown editors available on the web that you guys can stick in your website so that the wheel doesn't need to be reinvented.

**Comment by GuyInFridge** [comment]
Did you have any links to these markdown editors? To what extent would they improve our current set-up? We have a markdown library that @TommyHuang-dev set up which helps to render the Markdown text, but all the formatting tools were coded by us. Did you mean that some third-party editors could provide additional functionality on top of just rendering the Markdown text?

**Comment by ningsongshen** [comment]
I am unsure if they would improve your setup or if any new functionality would be provided (since MD can be just typed then rendered). However, they are available if your team finds that working on a custom editor is too onerous. These open-source projects are usually actively maintained and have a full array of features.

Here are some links (some I've used, some not):
https://github.com/pandao/editor.md
https://github.com/Ionaru/easy-markdown-editor
https://github.com/parpalak/upmath.me
